### PR TITLE
fixes to README and DATA-SOURCES-SELECTION

### PR DESCRIPTION
**Pull request by krsnapaudel**
* Fix example code in `README.md`.
* Fix DE data selection in `data_preparation/DATA-SOURCES-SELECTION.md`.
* Remove two LSTM init args not required.

### CODE REVIEW

**Comment by krsnapaudel** [comment]
@michielkallenberg Please take a look. Small changes.

**Review by michielkallenberg — APPROVED** [review]
LGTM; 
I noticed an issue in the notebook as well (that was using a deprecated "test_maize_US"); trying out some things with that now

**Comment by hbja** [comment]
If I take too long to review feel free to merge. I'm currently trying to run the benchmark.

**Comment by krsnapaudel** [comment]
Found and fixed "test_maize_us"

**Pull request merged**
