### PR TITLE
improve validation of workshop results

### PR DESCRIPTION
**Pull request by krsnapaudel**
* Improved validation of AgML workshop results. Now validating with both workshop data and CY-Bench data.
* Validation of workshop results with CY-Bench data aligned to crop season.
* Fix to crop season alignment bug #302
* Updates to README and CONTRIBUTING.

I have done my best to validate the fix to #302. It's very difficult to say if the fix is complete. We will find out when we run the benchmark for all countries.

### CODE REVIEW

**Comment by krsnapaudel** [comment]
Expected NRMSE from AgML workshop was around 25%.

Here are the results for workshop data:
```
workshop_lstm {'normalized_rmse': 26.31431758401148, 'mape': 0.3237316762210939}
benchmark_lstm {'normalized_rmse': 28.08270525164453, 'mape': 0.3588604904888184}
```
Then results for CY-Bench data:
```
workshop_lstm {'normalized_rmse': 24.910063575392375, 'mape': 0.279954145088608}
benchmark_lstm {'normalized_rmse': 24.608247336807583, 'mape': 0.26869526657056003}
```
Feel free to run the script with suggested changes to config.

**Comment by krsnapaudel** [comment]
@ellaampy: Would you be able to review and validate this? Thanks.

**Comment by krsnapaudel** [comment]
Comparison of benchmark results for some countries before and after the fix.

Before the fix for wheat, NL. LSTM trained for 10 epochs.
```
                   normalized_rmse           mape
model
AverageYieldModel         7.505560    0.066450
LSTM                     95.049157        0.946308
LinearTrend               7.681298       0.068056
SklearnRF                 8.727651      0.078002
SklearnRidge             99.518835     0.994273
```
After the fix for wheat, NL. LSTM trained for 10 epochs.
```
                   normalized_rmse           mape
model
AverageYieldModel         7.555941       0.066860
LSTM                     91.542768         0.909809
LinearTrend               7.795986       0.069346
SklearnRF                 8.537387      0.075884
SklearnRidge             56.841416      0.561018
```

**Review by michielkallenberg — APPROVED** [review]
LGTM

**Review by aikepotze — APPROVED** [review]
Looks good to me as well. Only thing I am worried about is the alignment w.r.t end of season and trimming of days at the start. This means that the start of season is not aligned, which might make the modelling more difficult. I'll create an issue for this.

**Pull request merged**
