### PR TITLE
Update tests to use cybench data

### PR DESCRIPTION
**Pull request by krsnapaudel**
* Pushed sample cybench data to `sample_data` repo.
* Updated tests to use the same data.

### CODE REVIEW

**Review by michielkallenberg — APPROVED** [review]
LGTM; mind the TODO for putting the nn_model test back

**Comment by michielkallenberg** [comment]
> LGTM; mind the TODO for putting the nn_model test back

Hmm test fails

**Review by michielkallenberg — CHANGES_REQUESTED** [review]
test fails

**Comment by krsnapaudel** [comment]
@michielkallenberg : Rerunning. should pass now.

**Comment by michielkallenberg** [comment]
LGTM

**Pull request merged**
